// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "dropbox-dir",
    behaviors: [window.DropboxItemBehavior],
    properties: {
      files: {
        notify: true,
        type: Array
      }
    },
    fetch: function(options) {
      if (options == null) {
        options = {};
      }
      return this.execute(function() {
        return this.instance.readdir(this.path, options, (function(_this) {
          return function(error, fileNames, folder, files) {
            _this.files = files;
            if (error != null) {
              return _this.fire("error", error);
            }
          };
        })(this));
      });
    },
    ready: function() {
      if (this.auto) {
        return this.fetch();
      }
    }
  });

}).call(this);

//# sourceMappingURL=dropbox-dir.js.map
